/**
 * Demo dataset for Business Finder.
 *
 * Coordinates are stored as small offsets from `config.seedCenter`, so pointing
 * the app at a different city (SEED_LAT / SEED_LNG) relocates the whole dataset
 * without touching this file.
 */

/** Weekly hour presets. Times are "HH:MM"; a closing time may pass midnight. */
export const HOUR_PRESETS = {
  standard: {
    0: ['10:00', '20:00'],
    1: ['09:00', '21:00'],
    2: ['09:00', '21:00'],
    3: ['09:00', '21:00'],
    4: ['09:00', '21:00'],
    5: ['09:00', '22:00'],
    6: ['09:00', '22:00'],
  },
  cafe: {
    0: ['07:00', '22:00'],
    1: ['06:30', '22:00'],
    2: ['06:30', '22:00'],
    3: ['06:30', '22:00'],
    4: ['06:30', '23:00'],
    5: ['06:30', '23:30'],
    6: ['07:00', '23:00'],
  },
  bakery: {
    0: ['05:30', '14:00'],
    1: ['05:30', '14:00'],
    2: ['05:30', '14:00'],
    3: ['05:30', '14:00'],
    4: ['05:30', '15:00'],
    5: ['05:30', '15:00'],
    6: ['06:00', '13:00'],
  },
  lateNight: {
    0: ['12:00', '25:00'],
    1: ['12:00', '25:00'],
    2: ['12:00', '25:00'],
    3: ['12:00', '26:00'],
    4: ['12:00', '27:00'],
    5: ['12:00', '27:00'],
    6: ['12:00', '26:00'],
  },
  evening: {
    0: ['17:00', '25:00'],
    1: ['17:00', '25:00'],
    2: ['17:00', '25:00'],
    3: ['17:00', '26:00'],
    4: ['17:00', '27:00'],
    5: ['17:00', '27:00'],
    6: ['17:00', '26:00'],
  },
  allDay: {
    0: ['00:00', '24:00'],
    1: ['00:00', '24:00'],
    2: ['00:00', '24:00'],
    3: ['00:00', '24:00'],
    4: ['00:00', '24:00'],
    5: ['00:00', '24:00'],
    6: ['00:00', '24:00'],
  },
  office: {
    0: ['08:00', '17:00'],
    1: ['08:00', '17:00'],
    2: ['08:00', '17:00'],
    3: ['08:00', '17:00'],
    4: ['08:00', '17:00'],
    5: null,
    6: ['09:00', '13:00'],
  },
  gym: {
    0: ['05:00', '23:00'],
    1: ['05:00', '23:00'],
    2: ['05:00', '23:00'],
    3: ['05:00', '23:00'],
    4: ['05:00', '23:00'],
    5: ['06:00', '22:00'],
    6: ['06:00', '23:00'],
  },
  shopLate: {
    0: ['10:00', '23:00'],
    1: ['10:00', '23:00'],
    2: ['10:00', '23:00'],
    3: ['10:00', '23:00'],
    4: ['10:00', '24:00'],
    5: ['10:00', '24:00'],
    6: ['10:00', '24:00'],
  },
};

export const CATEGORIES = [
  { id: 'restaurant', label: 'Restaurants', icon: '🍽️' },
  { id: 'cafe', label: 'Cafés', icon: '☕' },
  { id: 'bakery', label: 'Bakeries', icon: '🥐' },
  { id: 'grocery', label: 'Groceries', icon: '🛒' },
  { id: 'pharmacy', label: 'Pharmacies', icon: '💊' },
  { id: 'retail', label: 'Shops', icon: '🛍️' },
  { id: 'electronics', label: 'Electronics', icon: '📱' },
  { id: 'beauty', label: 'Beauty & Barbers', icon: '💈' },
  { id: 'fitness', label: 'Fitness', icon: '🏋️' },
  { id: 'nightlife', label: 'Nightlife', icon: '🎷' },
  { id: 'dessert', label: 'Desserts', icon: '🍨' },
  { id: 'books', label: 'Books', icon: '📚' },
  { id: 'kids', label: 'Kids & Fun', icon: '🎠' },
  { id: 'services', label: 'Services', icon: '🔧' },
  { id: 'health', label: 'Clinics', icon: '🩺' },
  { id: 'pets', label: 'Pets', icon: '🐾' },
];

/**
 * `updates` entries are [minutesAgo, kind, body] and optionally a 4th element
 * `{ promoted: true }`. They are what makes each profile feel alive.
 */
export const BUSINESSES = [
  {
    slug: 'golden-wok',
    name: 'Golden Wok',
    category: 'restaurant',
    tagline: 'Hand-pulled noodles and real Szechuan heat',
    description:
      'A family-run Chinese kitchen that has been feeding the neighbourhood for eleven years. Noodles are pulled to order, the chilli oil is made in-house every Monday, and the lunch set is still the best value on the street.',
    address: '14 Harbour Lane',
    phone: '+973 1720 4411',
    website: 'https://goldenwok.example',
    d: [0.004, -0.006],
    price: 2,
    rating: 4.6,
    ratingCount: 412,
    hours: 'standard',
    plan: 'premium',
    verified: true,
    tags: ['chinese', 'noodles', 'szechuan', 'spicy', 'dinner', 'lunch', 'family', 'dine-in', 'takeaway', 'halal'],
    updates: [
      [95, 'new', 'A new Szechuan chef just joined our kitchen. Come and taste authentic, fresh Chinese food this week.', { promoted: true }],
      [1500, 'offer', 'Lunch sets are 20% off Monday to Thursday, 12–3pm. Includes soup and jasmine tea.'],
      [4300, 'news', 'Our chilli oil is back in stock — small batch, made this morning.'],
    ],
    reviews: [
      ['Layla H.', 5, 'The dan dan noodles are genuinely the best I have had outside Chengdu.'],
      ['Marcus T.', 4, 'Busy at peak times but the food comes out fast and hot.'],
    ],
  },
  {
    slug: 'sunrise-bakery',
    name: 'Sunrise Bakery',
    category: 'bakery',
    tagline: 'Out of the oven, all morning long',
    description:
      'A tiny corner bakery with a big oven. Sourdough starts at six, croissants at seven, and the cinnamon rolls come out in batches until they run out — which they always do.',
    address: '3 Mill Street',
    phone: '+973 1733 8090',
    d: [-0.003, 0.005],
    price: 1,
    rating: 4.8,
    ratingCount: 289,
    hours: 'bakery',
    plan: 'featured',
    verified: true,
    tags: ['bread', 'sourdough', 'croissant', 'pastry', 'breakfast', 'cinnamon', 'coffee', 'vegetarian'],
    updates: [
      [25, 'stock', 'Warm cinnamon rolls are out of the oven right now.', { promoted: true }],
      [180, 'stock', 'Fresh sourdough is ready — 18 loaves on the rack.'],
      [2600, 'new', 'We are trialling a spelt and honey loaf this week. Tell us what you think.'],
    ],
    reviews: [
      ['Priya N.', 5, 'Get there before eight or the cinnamon rolls are gone. Worth the early alarm.'],
      ['Sam D.', 5, 'The sourdough crust is unreal.'],
    ],
  },
  {
    slug: 'the-corner-cup',
    name: 'The Corner Cup',
    category: 'cafe',
    tagline: 'Single-origin coffee, unhurried mornings',
    description:
      'Speciality coffee bar with a rotating single-origin filter, oat milk as standard, and enough plug sockets that nobody fights over them.',
    address: '77 Pearl Avenue',
    phone: '+973 1766 1200',
    d: [0.008, 0.009],
    price: 2,
    rating: 4.7,
    ratingCount: 631,
    hours: 'cafe',
    plan: 'premium',
    verified: true,
    tags: ['coffee', 'espresso', 'filter', 'wifi', 'laptop', 'breakfast', 'vegan', 'oat milk', 'brunch', 'quiet'],
    updates: [
      [40, 'new', 'This week on filter: a washed Ethiopian Guji. Bright, floral, tastes like apricot.'],
      [720, 'offer', 'Happy hour: any espresso drink half price between 3 and 5pm.'],
      [3000, 'news', 'New rule — laptops welcome all day except Saturday brunch.'],
    ],
    reviews: [
      ['Nour A.', 5, 'Best flat white in the city and the staff actually remember your order.'],
      ['James K.', 4, 'Fills up fast at weekends but the coffee is worth the wait.'],
    ],
  },
  {
    slug: 'green-fork',
    name: 'Green Fork',
    category: 'restaurant',
    tagline: 'Plant-based, all day',
    description:
      'A fully vegan kitchen doing bowls, mezze and a very good mushroom shawarma. Everything is made fresh daily and nothing on the menu contains animal products.',
    address: '22 Garden Row',
    phone: '+973 1744 3355',
    d: [-0.009, 0.002],
    price: 2,
    rating: 4.5,
    ratingCount: 208,
    hours: 'shopLate',
    plan: 'featured',
    tags: ['vegan', 'vegetarian', 'plant-based', 'healthy', 'bowls', 'salad', 'gluten-free', 'lunch', 'dinner', 'delivery'],
    updates: [
      [150, 'new', 'The mushroom shawarma is back on the menu permanently. You asked, loudly.'],
      [2000, 'offer', 'Student discount: 15% off with any valid student card, every day.'],
    ],
    reviews: [
      ['Hana R.', 5, 'Even my very carnivorous brother asked for seconds.'],
      ['Omar S.', 4, 'Portions are generous and the tahini is excellent.'],
    ],
  },
  {
    slug: 'city-pharmacy-24',
    name: 'City Pharmacy 24',
    category: 'pharmacy',
    tagline: 'Open every hour of every day',
    description:
      'A full-service pharmacy that genuinely never closes. Prescriptions, urgent supplies, baby formula at 3am, and a pharmacist on duty around the clock.',
    address: '1 Central Square',
    phone: '+973 1711 0000',
    d: [0.001, 0.001],
    price: 2,
    rating: 4.4,
    ratingCount: 517,
    hours: 'allDay',
    plan: 'premium',
    verified: true,
    tags: ['pharmacy', '24 hours', 'late', 'medicine', 'prescription', 'emergency', 'night', 'baby', 'first aid'],
    updates: [
      [60, 'news', 'Flu vaccines are in stock. Walk in, no appointment needed.'],
      [900, 'stock', 'Paediatric paracetamol restocked after last week’s shortage.'],
    ],
    reviews: [
      ['Dana M.', 5, 'Saved us at 2am with a sick toddler. The pharmacist was calm and kind.'],
    ],
  },
  {
    slug: 'midnight-diner',
    name: 'The Midnight Diner',
    category: 'restaurant',
    tagline: 'Still cooking when everywhere else has closed',
    description:
      'Burgers, breakfast and bottomless coffee served until the small hours. The griddle stays on until 2am on weekdays and 3am at weekends.',
    address: '40 Station Road',
    phone: '+973 1755 7788',
    d: [0.012, -0.011],
    price: 1,
    rating: 4.3,
    ratingCount: 954,
    hours: 'lateNight',
    plan: 'featured',
    tags: ['burgers', 'breakfast', 'late night', 'open late', '24', 'comfort food', 'coffee', 'diner', 'cheap'],
    updates: [
      [30, 'news', 'Kitchen is open and the griddle is hot. Come on in.'],
      [1400, 'offer', 'Night owls: free coffee refills after midnight.'],
    ],
    reviews: [
      ['Tariq B.', 4, 'The 1am cheeseburger is a civic service.'],
      ['Ella V.', 5, 'Friendly staff even at silly hours.'],
    ],
  },
  {
    slug: 'blue-note-lounge',
    name: 'Blue Note Lounge',
    category: 'nightlife',
    tagline: 'Live music six nights a week',
    description:
      'An intimate room with a proper piano, a short cocktail list and no cover charge before eight. Jazz on weekends, open mic on Tuesdays.',
    address: '9 Riverside Walk',
    phone: '+973 1799 2020',
    d: [0.006, 0.014],
    price: 3,
    rating: 4.6,
    ratingCount: 342,
    hours: 'evening',
    plan: 'premium',
    tags: ['jazz', 'live music', 'cocktails', 'bar', 'night', 'date night', 'evening', 'lounge'],
    updates: [
      [200, 'event', 'Live jazz tonight from nine. Free entry before eight.', { promoted: true }],
      [2900, 'event', 'Open mic every Tuesday — sign up from 7pm, ten-minute slots.'],
    ],
    reviews: [
      ['Rania F.', 5, 'Proper listening room. People actually stay quiet during the solos.'],
    ],
  },
  {
    slug: 'market-fresh-grocers',
    name: 'Market Fresh Grocers',
    category: 'grocery',
    tagline: 'Produce that arrived this morning',
    description:
      'An independent grocer working direct with local farms. Deliveries land before six every morning, so what you see on the shelf is what came off the truck today.',
    address: '58 Orchard Street',
    phone: '+973 1722 6161',
    d: [-0.006, -0.008],
    price: 2,
    rating: 4.5,
    ratingCount: 376,
    hours: 'shopLate',
    plan: 'featured',
    verified: true,
    tags: ['grocery', 'fruit', 'vegetables', 'produce', 'organic', 'local', 'fresh', 'shopping'],
    updates: [
      [55, 'stock', 'Fresh strawberries arrived this morning. First come, first served.', { promoted: true }],
      [1100, 'stock', 'Local figs are in season and on the front table.'],
      [3400, 'offer', 'Bag of misshapen veg — perfectly good, half price, every evening after 8pm.'],
    ],
    reviews: [
      ['Yousef A.', 5, 'Cheaper and fresher than the supermarket, and they know your name.'],
    ],
  },
  {
    slug: 'pixel-electronics',
    name: 'Pixel Electronics',
    category: 'electronics',
    tagline: 'Phones, laptops and honest advice',
    description:
      'An independent electronics shop with same-day screen repairs, genuine parts and staff who will happily tell you that you do not need the upgrade.',
    address: '12 Tech Plaza',
    phone: '+973 1788 4242',
    d: [0.015, 0.004],
    price: 3,
    rating: 4.2,
    ratingCount: 188,
    hours: 'shopLate',
    plan: 'premium',
    tags: ['electronics', 'phones', 'laptops', 'repair', 'accessories', 'gadgets', 'shopping', 'tech'],
    updates: [
      [80, 'stock', 'The new smartphone just landed. Only four left in stock.', { promoted: true }],
      [1700, 'news', 'Screen repairs now done in-store in under an hour.'],
    ],
    reviews: [
      ['Faisal Q.', 4, 'Fixed my laptop the same day for less than the official price.'],
    ],
  },
  {
    slug: 'the-wardrobe',
    name: 'The Wardrobe',
    category: 'retail',
    tagline: 'Independent clothing, carefully chosen',
    description:
      'A small boutique stocking a tight selection of labels you will not find in the mall, plus alterations by an in-house tailor.',
    address: '31 Linen Lane',
    phone: '+973 1777 5150',
    d: [-0.012, 0.012],
    price: 3,
    rating: 4.4,
    ratingCount: 121,
    hours: 'standard',
    plan: 'featured',
    tags: ['clothing', 'fashion', 'boutique', 'shopping', 'coats', 'tailor', 'gifts'],
    updates: [
      [300, 'offer', 'Winter coats, forty percent off, this weekend only.', { promoted: true }],
      [5000, 'new', 'Autumn collection is in — knitwear, wool and a lot of navy.'],
    ],
    reviews: [
      ['Sofia L.', 5, 'The tailoring is included and it is done properly.'],
    ],
  },
  {
    slug: 'sharp-and-co-barbers',
    name: 'Sharp & Co. Barbers',
    category: 'beauty',
    tagline: 'Walk in, walk out sharper',
    description:
      'Traditional barbering with hot towels and a straight razor, plus modern fades. Walk-ins welcome; the queue is shown live on our page.',
    address: '5 Anchor Street',
    phone: '+973 1766 9090',
    d: [0.003, -0.013],
    price: 2,
    rating: 4.7,
    ratingCount: 445,
    hours: 'standard',
    plan: 'free',
    tags: ['barber', 'haircut', 'shave', 'grooming', 'walk-in', 'beard', 'men'],
    updates: [
      [45, 'news', 'No queue right now — two chairs free.'],
      [2400, 'offer', 'Father and son cut: both for the price of one and a half, Sundays.'],
    ],
    reviews: [
      ['Ahmed Z.', 5, 'Best fade in the city, and they never rush.'],
    ],
  },
  {
    slug: 'ironworks-gym',
    name: 'Ironworks Gym',
    category: 'fitness',
    tagline: 'Open from five in the morning',
    description:
      'A serious, unfussy gym: free weights, platforms, chalk allowed. Classes morning and evening, and a sauna that actually gets hot.',
    address: '88 Foundry Road',
    phone: '+973 1733 2020',
    d: [-0.015, -0.003],
    price: 2,
    rating: 4.5,
    ratingCount: 267,
    hours: 'gym',
    plan: 'featured',
    tags: ['gym', 'fitness', 'weights', 'classes', 'early', 'sauna', 'training', 'workout'],
    updates: [
      [400, 'new', 'Two new squat racks and a full set of bumper plates arrived this week.'],
      [4800, 'offer', 'First class free, no card needed. Just turn up.'],
    ],
    reviews: [
      ['Nadia P.', 5, 'Opens at five which is the only reason I train at all.'],
    ],
  },
  {
    slug: 'scoop-and-swirl',
    name: 'Scoop & Swirl',
    category: 'dessert',
    tagline: 'Ice cream churned on site',
    description:
      'Twelve rotating flavours churned in the back, including three dairy-free. Cones, tubs and a very generous kids scoop.',
    address: '17 Seafront Promenade',
    phone: '+973 1744 8181',
    d: [0.01, 0.017],
    price: 1,
    rating: 4.8,
    ratingCount: 703,
    hours: 'shopLate',
    plan: 'premium',
    verified: true,
    tags: ['ice cream', 'dessert', 'kids', 'family', 'vegan', 'dairy-free', 'sweet', 'treat', 'weekend'],
    updates: [
      [20, 'new', 'Today’s new flavour: pistachio and rose. Churned an hour ago.'],
      [1300, 'event', 'Kids scoop half price all weekend — bring the small humans.'],
    ],
    reviews: [
      ['Maya J.', 5, 'The dairy-free chocolate is better than the dairy one.'],
    ],
  },
  {
    slug: 'chapter-one-books',
    name: 'Chapter One Books',
    category: 'books',
    tagline: 'A bookshop with opinions',
    description:
      'Independent bookshop with hand-written staff picks, a strong translated fiction section and a reading corner nobody will move you from.',
    address: '64 Quiet Lane',
    phone: '+973 1755 3131',
    d: [-0.004, 0.016],
    price: 2,
    rating: 4.9,
    ratingCount: 214,
    hours: 'standard',
    plan: 'free',
    tags: ['books', 'bookshop', 'reading', 'quiet', 'gifts', 'kids', 'events'],
    updates: [
      [600, 'event', 'Author reading this Thursday at 7pm. Twenty seats, free, first come.'],
      [3600, 'new', 'The translated fiction table has been completely refreshed.'],
    ],
    reviews: [
      ['Ines C.', 5, 'They recommended three books and all three were right.'],
    ],
  },
  {
    slug: 'little-explorers',
    name: 'Little Explorers Play Centre',
    category: 'kids',
    tagline: 'Somewhere to burn off the energy',
    description:
      'Indoor soft play, climbing frames and a craft room, split by age group so the toddlers are not trampled. Parents get decent coffee.',
    address: '2 Meadow Way',
    phone: '+973 1799 4040',
    d: [0.018, -0.004],
    price: 2,
    rating: 4.4,
    ratingCount: 356,
    hours: 'shopLate',
    plan: 'featured',
    tags: ['kids', 'family', 'children', 'play', 'weekend', 'fun', 'indoor', 'party', 'toddler'],
    updates: [
      [500, 'event', 'Weekend craft workshop: dinosaur painting, Saturday 10am and 2pm.', { promoted: true }],
      [2800, 'news', 'The new climbing wall is open for ages six and up.'],
    ],
    reviews: [
      ['Khalid R.', 4, 'Two hours of peace for the adults. Worth every fils.'],
    ],
  },
  {
    slug: 'petals-florist',
    name: 'Petals Florist',
    category: 'retail',
    tagline: 'Cut this morning, arranged while you wait',
    description:
      'A florist working with seasonal stems and no dyed carnations. Same-day delivery across the city if you order before two.',
    address: '26 Bloom Street',
    phone: '+973 1722 7373',
    d: [-0.008, -0.014],
    price: 2,
    rating: 4.6,
    ratingCount: 142,
    hours: 'standard',
    plan: 'free',
    tags: ['flowers', 'florist', 'gifts', 'delivery', 'wedding', 'bouquet', 'plants'],
    updates: [
      [700, 'stock', 'Peonies are in for a short season — about two weeks.'],
    ],
    reviews: [
      ['Zara W.', 5, 'They rescued my anniversary with an hour to spare.'],
    ],
  },
  {
    slug: 'harbour-clinic',
    name: 'Harbour Family Clinic',
    category: 'health',
    tagline: 'Same-day appointments, most days',
    description:
      'General practice with walk-in slots each morning, on-site lab tests, and a paediatric nurse five days a week.',
    address: '19 Marine Drive',
    phone: '+973 1711 5252',
    d: [0.005, 0.02],
    price: 3,
    rating: 4.3,
    ratingCount: 198,
    hours: 'office',
    plan: 'premium',
    verified: true,
    tags: ['clinic', 'doctor', 'health', 'appointment', 'family', 'paediatric', 'lab', 'walk-in'],
    updates: [
      [1000, 'news', 'Six same-day slots are open tomorrow morning. Call to book.'],
    ],
    reviews: [
      ['Reem T.', 4, 'Short wait and the doctor listened properly.'],
    ],
  },
  {
    slug: 'happy-paws',
    name: 'Happy Paws Pet Store',
    category: 'pets',
    tagline: 'Food, toys and a very patient groomer',
    description:
      'Pet supplies with a grooming room at the back. Nail trims without an appointment, and a freezer of raw food.',
    address: '45 Kennel Road',
    phone: '+973 1766 8484',
    d: [-0.017, 0.007],
    price: 2,
    rating: 4.5,
    ratingCount: 163,
    hours: 'standard',
    plan: 'free',
    tags: ['pets', 'dog', 'cat', 'grooming', 'pet food', 'supplies', 'vet'],
    updates: [
      [1600, 'offer', 'Grooming is 25% off midweek — Tuesday to Thursday.'],
    ],
    reviews: [
      ['Bilal N.', 5, 'The groomer is a saint. My dog is not an easy customer.'],
    ],
  },
  {
    slug: 'quickfix-hardware',
    name: 'QuickFix Hardware',
    category: 'services',
    tagline: 'The bit you need, in stock',
    description:
      'Old-fashioned hardware store with keys cut while you wait, paint mixed to order, and someone who knows which screw you actually need.',
    address: '71 Works Street',
    phone: '+973 1733 6767',
    d: [0.014, 0.011],
    price: 2,
    rating: 4.7,
    ratingCount: 231,
    hours: 'standard',
    plan: 'free',
    tags: ['hardware', 'tools', 'diy', 'keys', 'paint', 'repair', 'plumbing'],
    updates: [
      [2200, 'news', 'Key cutting is back — the machine is fixed and it is free with any purchase.'],
    ],
    reviews: [
      ['Hassan G.', 5, 'Twenty years of knowing exactly where everything is.'],
    ],
  },
  {
    slug: 'saffron-house',
    name: 'Saffron House',
    category: 'restaurant',
    tagline: 'Slow-cooked Persian classics',
    description:
      'Charcoal grill, saffron rice with a proper tahdig, and stews that take a day to make. Family sized platters for the table.',
    address: '8 Spice Court',
    phone: '+973 1788 1919',
    d: [-0.002, -0.017],
    price: 3,
    rating: 4.7,
    ratingCount: 388,
    hours: 'shopLate',
    plan: 'featured',
    verified: true,
    tags: ['persian', 'iranian', 'grill', 'kebab', 'rice', 'dinner', 'family', 'halal', 'date night'],
    updates: [
      [340, 'event', 'Friday feast: whole lamb shoulder for the table, must be pre-ordered.'],
      [4100, 'new', 'Tahdig is now available as a side on its own. You are welcome.'],
    ],
    reviews: [
      ['Parisa E.', 5, 'Tastes like my grandmother’s kitchen, which is the highest compliment I have.'],
    ],
  },
  {
    slug: 'brew-and-bind',
    name: 'Brew & Bind',
    category: 'cafe',
    tagline: 'Coffee, books and a lot of quiet',
    description:
      'Half café, half second-hand bookshop. No music before noon, generous power sockets, and a cat named Dewey.',
    address: '33 Paper Street',
    phone: '+973 1744 2323',
    d: [0.009, -0.016],
    price: 2,
    rating: 4.6,
    ratingCount: 275,
    hours: 'cafe',
    plan: 'free',
    tags: ['coffee', 'books', 'quiet', 'wifi', 'study', 'laptop', 'cake', 'vegetarian'],
    updates: [
      [850, 'news', 'Two hundred second-hand books just came in. Everything under three dinars.'],
    ],
    reviews: [
      ['Tom A.', 5, 'The only café in town where you can hear yourself think.'],
    ],
  },
  {
    slug: 'sandstone-laundry',
    name: 'Sandstone Laundry',
    category: 'services',
    tagline: 'Same-day wash and fold',
    description:
      'Drop off before ten, collect after five. Dry cleaning, alterations and a repair service for anything with a zip.',
    address: '52 Wash Lane',
    phone: '+973 1755 9494',
    d: [0.017, 0.016],
    price: 1,
    rating: 4.2,
    ratingCount: 97,
    hours: 'office',
    plan: 'free',
    tags: ['laundry', 'dry cleaning', 'wash', 'alterations', 'ironing', 'service'],
    updates: [
      [3200, 'offer', 'Ten kilos for the price of eight, every Sunday.'],
    ],
    reviews: [
      ['Grace O.', 4, 'Reliable and cheap. What more do you want from a laundry.'],
    ],
  },
  {
    slug: 'olive-and-thyme',
    name: 'Olive & Thyme',
    category: 'restaurant',
    tagline: 'Levantine mezze, generous portions',
    description:
      'Hot and cold mezze, charcoal grills and bread baked in the corner oven all evening. Large groups welcome with notice.',
    address: '11 Grove Terrace',
    phone: '+973 1799 5757',
    d: [-0.011, -0.01],
    price: 2,
    rating: 4.5,
    ratingCount: 522,
    hours: 'shopLate',
    plan: 'featured',
    tags: ['lebanese', 'mezze', 'grill', 'hummus', 'vegetarian', 'family', 'dinner', 'halal', 'groups'],
    updates: [
      [1200, 'offer', 'Mezze night: any eight dishes for a fixed price, Sunday to Tuesday.'],
    ],
    reviews: [
      ['Elias M.', 5, 'The bread never stops coming and that is the point.'],
    ],
  },
  {
    slug: 'lumen-optics',
    name: 'Lumen Optics',
    category: 'retail',
    tagline: 'Eye tests while you wait',
    description:
      'Independent opticians with same-week lenses, a free annual eye test, and frames that are not all owned by the same conglomerate.',
    address: '29 Vision Street',
    phone: '+973 1722 1414',
    d: [0.002, 0.013],
    price: 3,
    rating: 4.4,
    ratingCount: 118,
    hours: 'standard',
    plan: 'free',
    tags: ['optician', 'glasses', 'eye test', 'lenses', 'sunglasses', 'health'],
    updates: [
      [2600, 'offer', 'Second pair half price when you buy any frame this month.'],
    ],
    reviews: [
      ['Ruth B.', 4, 'Thorough test and no pressure to buy the expensive lenses.'],
    ],
  },
  {
    slug: 'la-tortilla',
    name: 'La Tortilla',
    category: 'restaurant',
    tagline: 'Tacos made properly',
    description:
      'Corn tortillas pressed to order, three salsas on every table, and a vegetarian al pastor that converts people.',
    address: '6 Sunset Alley',
    phone: '+973 1766 2727',
    d: [0.011, 0.006],
    price: 1,
    rating: 4.6,
    ratingCount: 449,
    hours: 'lateNight',
    plan: 'free',
    tags: ['mexican', 'tacos', 'late night', 'cheap', 'vegetarian', 'spicy', 'takeaway', 'lunch'],
    updates: [
      [110, 'stock', 'Al pastor is on the spit and carving now.'],
    ],
    reviews: [
      ['Diego F.', 5, 'Actual corn tortillas. Finally.'],
    ],
  },
  {
    slug: 'the-glass-house',
    name: 'The Glass House',
    category: 'cafe',
    tagline: 'Brunch under the skylights',
    description:
      'An all-day brunch spot in a converted greenhouse. Long waits at weekends, no bookings, endlessly photogenic.',
    address: '90 Botanic Road',
    phone: '+973 1733 3838',
    d: [-0.014, 0.017],
    price: 3,
    rating: 4.3,
    ratingCount: 812,
    hours: 'cafe',
    plan: 'featured',
    tags: ['brunch', 'breakfast', 'coffee', 'weekend', 'vegetarian', 'pancakes', 'date night', 'photogenic'],
    updates: [
      [420, 'news', 'Weekend wait is about 25 minutes right now. Put your name down and walk the gardens.'],
      [3900, 'new', 'New brunch menu: three new vegetarian plates and a very serious hash.'],
    ],
    reviews: [
      ['Amira D.', 4, 'Beautiful room, brilliant pancakes, come early.'],
    ],
  },
  {
    slug: 'northgate-mini-mart',
    name: 'Northgate Mini Mart',
    category: 'grocery',
    tagline: 'Open till midnight, every day',
    description:
      'The corner shop that has whatever you forgot. Milk, batteries, phone credit, ice, and a surprisingly good cheese counter.',
    address: '4 Northgate',
    phone: '+973 1711 6262',
    d: [0.019, 0.001],
    price: 1,
    rating: 4.1,
    ratingCount: 156,
    hours: 'shopLate',
    plan: 'free',
    tags: ['grocery', 'convenience', 'late', 'milk', 'snacks', 'ice', 'essentials', 'open late'],
    updates: [
      [1900, 'news', 'We now stock fresh bread from Sunrise Bakery, delivered daily at seven.'],
    ],
    reviews: [
      ['Nate H.', 4, 'Always open when I need it.'],
    ],
  },
  {
    slug: 'atlas-travel-cafe',
    name: 'Atlas Travel Café',
    category: 'cafe',
    tagline: 'Maps on the walls, decent sandwiches',
    description:
      'A café for people planning to be somewhere else. Guidebook library, big tables, and a soup that changes daily.',
    address: '38 Compass Court',
    phone: '+973 1744 4949',
    d: [-0.019, -0.006],
    price: 2,
    rating: 4.2,
    ratingCount: 88,
    hours: 'cafe',
    plan: 'free',
    tags: ['cafe', 'sandwiches', 'soup', 'wifi', 'quiet', 'lunch', 'vegetarian'],
    updates: [
      [2100, 'new', 'Soup of the day is roasted tomato with basil oil.'],
    ],
    reviews: [
      ['Ivy L.', 4, 'Lovely spot to plan a trip you cannot afford.'],
    ],
  },
  {
    slug: 'summit-outdoors',
    name: 'Summit Outdoors',
    category: 'retail',
    tagline: 'Kit for people who go outside',
    description:
      'Hiking, camping and climbing gear, with boot fitting by someone who has actually walked in them. Rentals available for tents and packs.',
    address: '21 Ridge Way',
    phone: '+973 1788 5858',
    d: [0.007, -0.019],
    price: 3,
    rating: 4.6,
    ratingCount: 174,
    hours: 'standard',
    plan: 'free',
    tags: ['outdoors', 'hiking', 'camping', 'climbing', 'boots', 'rental', 'sports', 'shopping'],
    updates: [
      [4400, 'offer', 'End of season: all summer tents 30% off while stock lasts.'],
    ],
    reviews: [
      ['Owen S.', 5, 'They spent forty minutes fitting my boots and did not upsell me once.'],
    ],
  },
  {
    slug: 'velvet-nails-spa',
    name: 'Velvet Nails & Spa',
    category: 'beauty',
    tagline: 'Late appointments, seven days',
    description:
      'Manicures, pedicures and facials with appointments running until nine. Walk-ins taken whenever a chair is free.',
    address: '15 Rose Arcade',
    phone: '+973 1799 7171',
    d: [-0.005, 0.019],
    price: 2,
    rating: 4.4,
    ratingCount: 302,
    hours: 'shopLate',
    plan: 'featured',
    tags: ['nails', 'spa', 'manicure', 'facial', 'beauty', 'late', 'appointment', 'women'],
    updates: [
      [260, 'news', 'Two evening slots opened up tonight after a cancellation.'],
    ],
    reviews: [
      ['Salma K.', 4, 'Clean, calm and they actually run on time.'],
    ],
  },
];

export const REVIEW_FALLBACKS = [
  ['Jordan M.', 4, 'Solid every time. Glad it is on my street.'],
  ['Aisha R.', 5, 'Friendly staff and fair prices.'],
  ['Chris P.', 4, 'Does exactly what it says. No complaints.'],
];
